spring.datasource.url=jdbc:postgresql://localhost:5432/poc_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.threads.virtual.enabled=true

# Habilitar CORS para que el frontend pueda llamar al backend
endpoints.cors.allowed-origins=*
